name: finale_chat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  animated_text_kit: ^4.2.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  modal_progress_hud_nsn: ^0.5.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - images/