// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHrQIGr193dfQ7yiFIgguNLYxLKUyycos',
    appId: '1:467658023889:web:33c7b88471f3ff368d76f0',
    messagingSenderId: '467658023889',
    projectId: 'finale-chat-a1d63',
    authDomain: 'finale-chat-a1d63.firebaseapp.com',
    storageBucket: 'finale-chat-a1d63.appspot.com',
    measurementId: 'G-KB4SBE0BVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYZBNkgSe4WaUdG5WtJCba2siPS7O9J-o',
    appId: '1:467658023889:android:5bbb63549355fd478d76f0',
    messagingSenderId: '467658023889',
    projectId: 'finale-chat-a1d63',
    storageBucket: 'finale-chat-a1d63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5nFfiDugbUn45CqY8MMkYqlWhq92UHtg',
    appId: '1:467658023889:ios:6241582a7d21c55d8d76f0',
    messagingSenderId: '467658023889',
    projectId: 'finale-chat-a1d63',
    storageBucket: 'finale-chat-a1d63.appspot.com',
    iosBundleId: 'com.example.finaleChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5nFfiDugbUn45CqY8MMkYqlWhq92UHtg',
    appId: '1:467658023889:ios:6241582a7d21c55d8d76f0',
    messagingSenderId: '467658023889',
    projectId: 'finale-chat-a1d63',
    storageBucket: 'finale-chat-a1d63.appspot.com',
    iosBundleId: 'com.example.finaleChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHrQIGr193dfQ7yiFIgguNLYxLKUyycos',
    appId: '1:467658023889:web:a3b9ef8ce0ddcb0e8d76f0',
    messagingSenderId: '467658023889',
    projectId: 'finale-chat-a1d63',
    authDomain: 'finale-chat-a1d63.firebaseapp.com',
    storageBucket: 'finale-chat-a1d63.appspot.com',
    measurementId: 'G-SET0V0NEVX',
  );
}
